const soundFiles =  ['a covered it.wav',
'a use different voices everytime i go in.wav',
'accidently blowing up osama bin laden.wav',
'ad kill you bro.wav',
'ad smash your head off with a thing.wav',
'ak47.wav',
'alton towers got a spa bro.wav',
'am fucking loaded.wav',
'am not joking bro.wav',
'am not.wav',
'and fucking run you over with tractor.wav',
'and nice fit arses too man.wav',
'and_images_are_haram.wav',
'arab laugh 2.wav',
'arab laugh.wav',
'arab scream.wav',
'arabic.wav',
'are you in paradise bro.wav',
'a_thought_u_recording_it.wav',
'blowing up your slag sister.wav',
'bomb the mosque radequilise the moderators bring it all on.wav',
'bomb the mosque.wav',
'brother.wav',
'can a have-------------------12 bottles of bleach please.wav',
'can i cook mine.wav',
'can i have 12 bottles of bleach please.wav',
'cant do a jihadi video with a box on your head.wav',
'chickencottage_propahalal_bargainbucket_699.wav',
'cos al turn you baked beaks alright.wav',
'crow explosion.wav',
'dancing in the moonlight (van singing).wav',
'die smiling bro.wav',
'do they.wav',
'eyup_youunbelieving_kufah_bastards.wav',
'flippin heck man would ya.wav',
'flippin pop it brother.wav',
'flippin_idiots.wav',
'fly it into tower full of jews and slags.wav',
'for jihad man.wav',
'fuck mini babybells.wav',
'fucking boy george.wav',
'fuckoff bro east is that way.wav',
'fuckoff out my house.wav',
'fuckoff.wav',
'gone paradise init brother omar.wav',
'got loads of liquid piroxcide.wav',
"he's a jew.wav",
"he's the first hero of the final jihad.wav",
'hold onto these when i press clicky just think about taking out kufah.wav',
'how often do you go to mosque.wav',
'how old are ye.wav',
'i am the invisible jihadi.wav',
'i am the most al qaeda one here.wav',
'i dont argue with women.wav',
"i just finish this then we're all off to heaven awrite.wav",
'i said i was gonna bomb something else.wav',
'i think am gonna go now bro.wav',
'im already in the mujahadin.wav',
'internet.wav',
'IRA Voice.wav',
"its the parts they're jewish.wav",
'jews invented sparkplugs to control global traffic.wav',
'lets bomb boots.wav',
'ma brain is ma heart.wav',
'ma plan is rite.wav',
'make a fucking meal of it.wav',
'maybe it wer gods will.wav',
'mujhad brothers.wav',
'mushallah brother #2.wav',
'mushallah brother.wav',
'music 1.wav',
'no you confused bro.wav',
'not fucking messing now yeah.wav',
'not_too_small_brother.wav',
'okay we can talk about girls.wav',
'omar.wav',
'once or twice.wav',
'ones with big jubblies and that.wav',
'or some other such slag utlity.wav',
'paki bashing.wav',
'paki rambo.wav',
'Police Raid.wav',
'propa halal.wav',
'propa mujahid ad wiz in me own mouth.wav',
'propa mujahid yeah.wav',
'propa_replica_man.wav',
'replica_ak47.wav',
"right he's buying nukes for israel bro he's a jew.wav",
'right_what_you_looking_at.wav',
'rpg.wav',
'rubber dingy rabits 3.wav',
'rubber dingy rapids 1.wav',
'rubber dingy rapids 2.wav',
'rubber dingy rapids yeah brother.wav',
'salam lads.wav',
'shut up.wav',
'shut_up_barry.wav',
'tell me what to do bro.wav',
'that wholesale shop down the road.wav',
'thatll_bigger_it.wav',
'thats why its right yeah.wav',
'theres_nothing_there.wav',
'they sell condoms that make you wanna bang white girls.wav',
'to put a bomb on a crow.wav',
'we dont have to use this on ourselves do with barrry.wav',
'we got women talking back we got people playing stringed instruments.wav',
'WE RADEQUILISE THE MODERATES IT ALL KICKS OFF.wav',
"we'll blow up internet for brother faisal.wav",
'what #2.wav',
'what am a doing brother.wav',
'what parts in a car are jewish.wav',
'what you can fuck her but you cant kill her whats wrong with you.wav',
'what you saying.wav',
'what.wav',
'whats omar say.wav',
'what_for_action_man.wav',
'where it rises ya benchode paki prong.wav',
'who asked you fuckbrain.wav',
'who gives a fuck about a dead afghanis disneyland.wav',
'yeah.wav',
'you eat your simcard.wav',
'you fucking idiot.wav',
'you punch yourself in the face.wav',
"you'll be in paradise before me bro.wav"];

const backgrounds = ['1.jpg', '2.jpg', '3.jpg', '4.jpg', '5.jpg', '6.jpg', '7.jpg', '8.jpg'];